apiVersion: v1
kind: Secret
metadata:
  name: aelora-secret
stringData:
  AELORA_VALKEY_USERNAME: ""
  AELORA_VALKEY_PASSWORD: ""
  AELORA_POSTGRES_DSN: "postgres://postgres:postgres@postgres:5432/aelora?sslmode=disable"
  AELORA_COGNITO_REGION: "us-east-1"
  AELORA_COGNITO_USER_POOL_ID: "us-east-1_xxxxx"
  AELORA_COGNITO_APP_CLIENT_ID: "xxxxxxxx"
